#!/bin/bash
#SBATCH --job-name=Spaceranger_GIN65
#SBATCH --output=/home/imartinezle/spatial_transcriptomics/Spatial_Transcriptomics_Analysis/RESULTADOS/Spaceranger_GEX_GIN65.out
#SBATCH --error=/home/imartinezle/spatial_transcriptomics/Spatial_Transcriptomics_Analysis/RESULTADOS/Spaceranger_GEX_GIN65.err
#SBATCH --cpus-per-task=8
#SBATCH --mem=64G
#SBATCH --time=24:00:00
#SBATCH --partition=short
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=imartinezle@alumni.unav.es


module load SpaceRanger


spaceranger count \
    --id="GIN65" \
    --transcriptome="/home/imartinezle/Referencias/refdata-gex-GRCh38-2024-A" \
    --image="/home/imartinezle/spatial_transcriptomics/Spatial_Transcriptomics_Analysis/GIN65_3T_3.tif" \
    --slide=V14M06-322 \
    --area="B1" \
    --fastqs="/home/imartinezle/spatial_transcriptomics/Spatial_Transcriptomics_Analysis/GIN65" \
    --sample="GIN-65-3T-3" \
    --loupe-alignment="/home/imartinezle/spatial_transcriptomics/Spatial_Transcriptomics_Analysis/LoopBrowserEnric/GIN-65-3T-3/V14M06-322-B1_reviewed.json" \
    --create-bam=true \
    --output-dir="/home/imartinezle/spatial_transcriptomics/Spatial_Transcriptomics_Analysis/RESULTADOS/GIN65"
