#!/bin/bash
#SBATCH --job-name=Spaceranger_GIN63
#SBATCH --output=/home/imartinezle/spatial_transcriptomics/Spatial_Transcriptomics_Analysis/RESULTADOS/Spaceranger_GEX_GIN63.out
#SBATCH --error=/home/imartinezle/spatial_transcriptomics/Spatial_Transcriptomics_Analysis/RESULTADOS/Spaceranger_GEX_GIN63.err
#SBATCH --cpus-per-task=8
#SBATCH --mem=64G
#SBATCH --time=24:00:00
#SBATCH --partition=short
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=imartinezle@alumni.unav.es


module load SpaceRanger


spaceranger count \
    --id="GIN63" \
    --transcriptome="/home/imartinezle/Referencias/refdata-gex-GRCh38-2024-A" \
    --image="/home/imartinezle/spatial_transcriptomics/Spatial_Transcriptomics_Analysis/GIN63_3T_1.tif" \
    --slide=V14M06-322 \
    --area="A1" \
    --fastqs="/home/imartinezle/spatial_transcriptomics/Spatial_Transcriptomics_Analysis/GIN63" \
    --sample="GIN-63-3T-1" \
    --loupe-alignment="/home/imartinezle/spatial_transcriptomics/Spatial_Transcriptomics_Analysis/LoopBrowserEnric/GIN-63-3T-1/V14M06-322-D1_reviewed.json" \
    --create-bam=true \
    --output-dir="/home/imartinezle/spatial_transcriptomics/Spatial_Transcriptomics_Analysis/RESULTADOS/GIN63"
