#!/bin/bash
#SBATCH --job-name=Spaceranger_GIN71
#SBATCH --output=/home/imartinezle/spatial_transcriptomics/Spatial_Transcriptomics_Analysis/RESULTADOS/Spaceranger_GEX_GIN71.out
#SBATCH --error=/home/imartinezle/spatial_transcriptomics/Spatial_Transcriptomics_Analysis/RESULTADOS/Spaceranger_GEX_GIN71.err
#SBATCH --cpus-per-task=8
#SBATCH --mem=64G
#SBATCH --time=24:00:00
#SBATCH --partition=short
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=imartinezle@alumni.unav.es


module load SpaceRanger


spaceranger count \
    --id="GIN71" \
    --transcriptome="/home/imartinezle/Referencias/refdata-gex-GRCh38-2024-A" \
    --image="/home/imartinezle/spatial_transcriptomics/Spatial_Transcriptomics_Analysis/GIN71_3T_1.tif" \
    --slide=V14M06-322 \
    --area="D1" \
    --fastqs="/home/imartinezle/spatial_transcriptomics/Spatial_Transcriptomics_Analysis/GIN71" \
    --sample="GIN-71-3T-1" \
    --loupe-alignment="/home/imartinezle/spatial_transcriptomics/Spatial_Transcriptomics_Analysis/LoopBrowserEnric/GIN-71-3T-1/V14M06-322-D1_reviewed.json" \
    --create-bam=true \
    --output-dir="/home/imartinezle/spatial_transcriptomics/Spatial_Transcriptomics_Analysis/RESULTADOS/GIN71"
